{{- $configmapName := include "configmap.fullname" . }}
{{- $tracing := (include "common.tracing.merged" .) | fromYaml }}
{{- $metrics := (include "common.metrics.merged" .) | fromYaml }}
{{- $serviceUrls := (include "common.serviceUrls.merged" .) | fromYaml }}
{{- $storage := (include "common.storage.merged" .) | fromYaml }}
{{- $jobDefinitions := (include "common.jobDefinitions.merged" .) | fromYaml }}

{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $configmapName }}
data:
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  LOG_PINO_CALLER_ENABLED: {{ .Values.env.logPinoCallerEnabled | quote }}
  {{ if $tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracing.url }}
  {{ end }}
  {{ if $metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metrics.url }}
  TELEMETRY_METRICS_INTERVAL: {{ $metrics.interval | quote }}
  TELEMETRY_METRICS_BUCKETS: {{ $metrics.buckets | toJson | quote }}
  {{ end }}
  npm_config_cache: /tmp/

  HTTP_RETRY_ATTEMPTS: {{ .Values.env.httpRetry.attempts | quote }}
  HTTP_RETRY_DELAY: {{ .Values.env.httpRetry.delay | quote }}
  HTTP_RETRY_RESET_TIMEOUT: {{ .Values.env.httpRetry.resetTimeout | quote }}
  DISABLE_HTTP_CLIENT_LOGS: {{ .Values.env.disableHttpClientLogs | quote }}
  JOB_MANAGER_BASE_URL: {{ $serviceUrls.jobManager | quote}}
  HEARTBEAT_BASE_URL: {{ $serviceUrls.heartbeatManager | quote}}
  HEARTBEAT_INTERVAL_MS: {{ $jobDefinitions.config.heartBeat.intervalMs | quote }}
  DEQUEUE_INTERVAL_MS: {{ $jobDefinitions.config.dequeueIntervalMs | quote }}
  TILES_STORAGE_PROVIDER: {{ $storage.tilesStorageProvider | quote }}
  INGESTION_POLLING_INIT_TASK: {{ $jobDefinitions.tasks.init.type | quote }}
  INGESTION_POLLING_FINALIZE_TASK: {{ $jobDefinitions.tasks.finalize.type | quote }}
  INGESTION_NEW_JOB_TYPE: {{ $jobDefinitions.jobs.new.type | quote }}
  INGESTION_UPDATE_JOB_TYPE: {{ $jobDefinitions.jobs.update.type | quote }}
  INGESTION_SWAP_UPDATE_JOB_TYPE: {{ $jobDefinitions.jobs.swapUpdate.type | quote }}
  INGESTION_SEED_JOB_TYPE : {{ $jobDefinitions.jobs.seed.type | quote }}
  TILES_MERGING_TASK_TYPE: {{ $jobDefinitions.tasks.merge.type | quote }}
  TILES_MERGING_TILE_BATCH_SIZE: {{ $jobDefinitions.tasks.merge.tileBatchSize | quote }}
  TILES_MERGING_TASK_BATCH_SIZE: {{ $jobDefinitions.tasks.merge.taskBatchSize | quote }}
  TILES_SEEDING_TASK_TYPE: {{ $jobDefinitions.tasks.seed.type | quote }}
  TILES_SEEDING_GRID : {{ $jobDefinitions.tasks.seed.grid | quote }}
  TILES_SEEDING_MAX_ZOOM : {{ $jobDefinitions.tasks.seed.maxZoom | quote }}
  TILES_SEEDING_SKIP_UNCACHED : {{ $jobDefinitions.tasks.seed.skipUncached | quote }}
  MAPPROXY_API_URL: {{ $serviceUrls.mapproxyApi | quote }}
  GEOSERVER_API_URL: {{ $serviceUrls.geoserverApi | quote }}
  CATALOG_MANAGER_URL: {{ $serviceUrls.catalogManager | quote }}
  MAPPROXY_DNS: {{ $serviceUrls.mapServerPublicDNS | quote }}
  POLYGON_PART_MANAGER_URL: {{ $serviceUrls.polygonPartManager | quote }}
  GEOSERVER_WORKSPACE: {{ .Values.global.geoserver.workspace | quote }}
  GEOSERVER_DATASTORE: {{ .Values.global.geoserver.dataStore | quote }}
{{- end }}
