{
 "title": "Overseer Metrics",
 "description": "Dashboard for monitoring task processing metrics in the Overseer system",
 "tags": [
  "task-processing",
  "overseer"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "jobType",
    "query": {
     "query": "label_values(overseer_tasks_processed_total, jobType)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(nodejs_version_info{namespace=\"$namespace\",app=\"$app\"},pod)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values({app=\"$app\"},namespace)"
    }
   },
   { "name": "app", "query": "overseer" }
  ]
 },
 "panels": [
  {
   "title": "Task Completed and Failed ($jobType)",
   "type": "stat",
   "description": "Breakdown of task completed and failed count",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "repeat": "jobType",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(overseer_tasks_success_total{namespace=\"$namespace\",pod=~\"$pod\",jobType='$jobType', app=\"$app\"}) by (jobType, taskType, pod)",
     "legendFormat": "Completed - {{jobType}} - {{taskType}}"
    },
    {
     "expr": "sum(overseer_tasks_failure_total{app=\"$app\", namespace=\"$namespace\",pod=~\"$pod\",jobType='$jobType'}) by (jobType, taskType, errorType, pod)",
     "legendFormat": "Failed - {{jobType}} - {{taskType}} - {{errorType}}"
    }
   ]
  },
  {
   "title": "Tasks Processing Duration (${jobType})",
   "type": "timeseries",
   "description": "Distribution of task processing durations",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "repeat": "jobType",
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(overseer_tasks_processing_duration_seconds_sum{namespace=\"$namespace\",pod=~\"$pod\",jobType='$jobType', app='$app'}[$__interval])) by (pod, taskType)\n/ \nsum(rate(overseer_tasks_processing_duration_seconds_count{namespace=\"$namespace\",pod=~\"$pod\",jobType='$jobType', app='$app'}[$__interval])) by (pod, taskType)",
     "legendFormat": "sum - {{jobType}} - {{taskType}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(overseer_tasks_processing_duration_seconds_bucket{namespace=\"$namespace\",pod=~\"$pod\",jobType='$jobType', app='$app'}[$__interval])) by (le, pod, taskType))",
     "legendFormat": "p50 - {{jobType}} - {{taskType}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(overseer_tasks_processing_duration_seconds_bucket{namespace=\"$namespace\",pod=~\"$pod\",jobType='$jobType', }[$__interval])) by (le, pod, taskType))",
     "legendFormat": "p90 - {{jobType}} - {{taskType}}"
    }
   ]
  },
  {
   "title": "tiles-merging tasks for current job ($jobType))",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
   "repeat": "jobType",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(overseer_total_tiles_merging_tasks_created_per_job{namespace=\"$namespace\",pod=~\"$pod\",jobType='$jobType', app='$app'}) by (jobType, taskType, pod)",
     "legendFormat": "Task Count: {{jobType}}-{{taskType}}"
    },
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Batch total count per job ($jobType)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 24 },
   "repeat": "jobType",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(overseer_total_tiles_merging_batch_created_per_job{namespace=\"$namespace\",pod=~\"$pod\",jobType='$jobType', app='$app'}) by (jobType, taskType, pod)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}