apiVersion: v2
name: overseer
description: Helm chart for overseer service
type: application
version: 2.5.2
appVersion: 2.5.2
dependencies:
  - name: mclabels
    version: 1.0.1
    repository: oci://acrarolibotnonprod.azurecr.io/helm/infra
